# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Gitten' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Gitten

end
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
